package com.bidding.auction.bids;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

import com.bidding.auction.Transaction.Transaction;
import com.bidding.auction.product.Product;
import com.bidding.auction.user.User;
import com.fasterxml.jackson.annotation.JsonIgnore;
/**
 * class representing table that holds bids placed by user
 */
@Entity
public class Bid {
    @Id
    @GeneratedValue//value is automatically generated by springboot
    private Integer bid_id;//id of the bid
    private Integer bid_price;//price of the bid
    private Date time_placed;//time bid was place
    @JsonIgnore//do not return users in bids bean
    @ManyToOne(fetch = FetchType.LAZY)//many to one relationship between bids and user
    private User user;//user who has placed the bid
    @JsonIgnore//product the bid has been place on
    @ManyToOne(fetch = FetchType.LAZY)//relationship between bid and product
    private Product product;//product the bid has been placed on
    @OneToOne//relation ship between bid and the transaction place on it
    private Transaction bidTrans;
    private String bidstatus;
    /**
     * contructor used by springbood
     */
    protected Bid(){

    }
     /**
      * constructor that is called when the bid object is created
      * @param bid_id id of the bid
      * @param bid_price bid price
      * @param time_placed time bid is placed
      * @param user user placing the bid
      * @param product product the bid is placed on
      */
    public Bid(Integer bid_id,Integer bid_price,Date time_placed,User user,Product product,String bidstatus){
        this.bid_id=bid_id;
        this.bid_price=bid_price;
        this.time_placed=time_placed;
        this.user=user;
        this.product=product;
        this.bidstatus=bidstatus;

    }
    /**
     * setters and getters for the bid class
     * @param user
     */
    
    public void setUser(User user){
        this.user=user;
    }
    public void setBid_id(Integer bid_id) {
        this.bid_id = bid_id;
    }
    public void setProduct(Product product) {
        this.product = product;
    }
    public void setBid_price(Integer bid_price) {
        this.bid_price = bid_price;
    }
    public void setTime_placed(Date time_placed) {
        this.time_placed = time_placed;
    }
    public Integer getBid_id() {
        return bid_id;
    }
    public Integer getBid_price() {
        return bid_price;
    }
    public Date getTime_placed() {
        return time_placed;
    }
    public Product getProduct() {
        return product;
    }
    public User getUser() {
        return user;
    }
    public void setBidstatus(String bidstatus) {
        this.bidstatus = bidstatus;
    }
    public String getBidstatus() {
        return bidstatus;
    }
    /**
     * to string method used by springboot
     */
    @Override
    public String toString() {
        return String.format("[id:%s,bid-price:%s,time-palced:%s]", bid_id,bid_price,time_placed);
    }
}
